version: 2.1

jobs:
  scan:
    docker:
      # circleci ignores the entrypoint of debricked-scan, so start the scan manually with a step
      - image: debricked/cli 
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: debricked scan

workflows:
  debricked-scan:
    jobs:
      - scan
