version: latest

jobs:
  scan:
    docker:
      # circleci ignores the entrypoint of debricked-scan, so start the scan manually with a step
      - image: debricked/scan 
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo 

workflows:
  debricked-scan:
    jobs:
      - scan
